#Config file for the AutoPlant Plugin.
#Here you are able to change the in-game messages sent to the players while using the plugin*.

#*It is recommended that you keep the original messages for title formatting reasons.

#Plugin accepts both &f and [#FFFFFF] formatting codes.

#This field allows you to change the message when a sapling is broken:
Sapling: "[#1ed72c]That [#21bd21]tree [#21a317]isn't [#1f8a0e]fully [#1a7206]grown [#257e08]yet!"

#This field allows you to change the message when a crop is broken:
Crop: "[#1ed72c]That [#21bd21]crop [#21a317]isn't [#1f8a0e]fully [#1a7206]grown [#257e08]yet!"

#Once you have edited a title, be sure to reload the config using '/autoplant reload'.
#If you have any issue with the config file, you can delete the file, restart the server, and a new one will generated.